name: Build Site

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    # Skip if commit message contains [skip ci]
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    # Add permission to push to the repository
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        # Use token for authentication
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Check PowerShell Installation
      run: |
        if ! command -v pwsh &> /dev/null; then
          echo "PowerShell not found. Installing..."
          # Add Microsoft repository
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-debian-bullseye-prod bullseye main" > /etc/apt/sources.list.d/microsoft.list'
          # Install PowerShell
          sudo apt-get update
          sudo apt-get install -y powershell
        else
          echo "PowerShell is already installed"
          pwsh --version
        fi
      shell: bash
    
    - name: Create dist directory
      run: mkdir -p dist
      shell: bash

    - name: Build site
      shell: pwsh
      run: |
        Write-Host "PowerShell Version: $($PSVersionTable.PSVersion)"
        $env:OUTPUT_DIR = "dist"
        ./build.ps1

    - name: Commit built files
      # Only commit if this is a push to main, not a PR
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      env:
        GIT_AUTHOR_NAME: ${{ vars.GIT_AUTHOR_NAME || 'GitHub Action' }}
        GIT_AUTHOR_EMAIL: ${{ vars.GIT_AUTHOR_EMAIL || 'action@github.com' }}
      run: |
        git config --local user.email "${GIT_AUTHOR_EMAIL}"
        git config --local user.name "${GIT_AUTHOR_NAME}"
        git add dist/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-build: Update built files [skip ci]"
          git push
        fi
      shell: bash

    - name: Setup SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.TFPTUSERPRIVSSH }}
        SSH_KNOWN_HOSTS: ${{ vars.TFWEBHOST }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        ssh-keyscan -H "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts 2>/dev/null
      shell: bash
    
    - name: Deploy via SFTP
      env:
        REMOTE_USER: ${{ vars.SFTPUSERCERT }}
        REMOTE_HOST: ${{ vars.TFWEBHOST }}
      run: |
        cd dist
        # Create a list of files to upload
        find . -type f -print0 | while IFS= read -r -d '' file; do
          # Create the directory structure on the remote server
          ssh $REMOTE_USER@$REMOTE_HOST "mkdir -p /var/www/html/$(dirname ${file:2})"
          # Upload the file
          scp -r "$file" "$REMOTE_USER@$REMOTE_HOST:/var/www/html/${file:2}"
        done
      shell: bash

    - name: Cleanup
      if: always()
      run: |
        rm -f ~/.ssh/id_rsa
        rm -rf ~/.ssh/known_hosts 